// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"cron/cron/internal/logic"
	"cron/cron/internal/svc"

	"github.com/zeromicro/go-zero/rest"

	"github.com/robfig/cron/v3"

)

func RegisterCrontabs(server *rest.Server, serverCtx *svc.ServiceContext) {
	c := cron.New()
	//
	cronJob := func(svcCtx *svc.ServiceContext) func() {
		return func() {
			logic.NewCronLogic(svcCtx).RunScript()
		}
	}(serverCtx)
	c.AddFunc("*/10 * * * *", cronJob)

	c.Start()
}
