// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterReq struct {
	Email    string `json:"email,optional" validate:"required,email" label:"邮箱"`
	Name     string `json:"name,optional" validate:"required,max=50" label:"用户名"`
	Password string `json:"password,optional" validate:"required" label:"密码"`
}

type UserRegisterReply struct {
	Message string `json:"message"`
}

type UserLoginReq struct {
	Email    string `json:"email,optional" validate:"required,email" label:"邮箱"`
	Password string `json:"password,optional" validate:"required" label:"密码"`
}

type UserLoginReply struct {
	Token string `json:"token"`
}

type ChatReq struct {
	Channel string `json:"channel,optional" validate:"required,oneof=wecom openai" label:"渠道"`
	MSG     string `json:"msg,optional" validate:"required,max=500" label:"消息"`
	UserID  string `json:"user_id,optional" validate:"required,max=500" label:"用户标识"`
	AgentID int64  `json:"agent_id,optional" validate:"required" label:"应用标识"`
}

type ChatReply struct {
	Message string `json:"message"`
}

type CustomerChatReq struct {
	MsgID      string `json:"msg_id"`
	Msg        string `json:"msg"`
	CustomerID string `json:"customer_id"`
	OpenKfID   string `json:"open_kf_id"`
}

type CustomerChatReply struct {
	Message string `json:"message"`
}

type ChatHistoryExportReq struct {
	UserNickname string `json:"user_nickname"`
	KfName       string `json:"kf_name"`
	ChatType     int32  `json:"chat_type"`
	StartTime    string `json:"start_time,omitempty"`
	EndTime      string `json:"end_time,omitempty"`
}

type ChatHistoryExportReply struct {
	File string `json:"file"`
}

type GetLastChatInfoRequest struct {
	UserNickname string `json:"user_nickname"`
	KfName       string `json:"kf_name"`
	ChatType     int32  `json:"chat_type"`
}

type GetLastChatInfoReply struct {
	ReqContent  string `json:"req_content"`
	ResContent  string `json:"res_content"`
	CreatedTime string `json:"created_time"`
}

type DoGenerateActiveChatContentRequest struct {
	UserNickname   string `json:"user_nickname"`
	KfName         string `json:"kf_name"`
	Prompt         string `json:"prompt"`
	ContextMessage string `json:"context_message"`
	ChatType       int32  `json:"chat_type"`
}

type DoGenerateActiveChatContentReply struct {
	Message string `json:"message"`
}

type UploadArticleHandlerReq struct {
}

type UploadArticleHandlerReply struct {
	Message string `json:"message"`
}

type DeleteCollectionHandlerReq struct {
	CollectionName string `json:"collection_name"`
}

type DeleteCollectionHandlerReply struct {
	Message string `json:"message"`
}

type DownloadChatHistoryReply struct {
}

type DownloadChatHistoryReq struct {
	File string `form:"file"`
}

type SetPromptReq struct {
	KfId   string `json:"kf_id"`
	Prompt string `json:"prompt"`
}

type SetPromptReply struct {
	Message string `json:"message"`
}

type ListPromptReq struct {
}

type ListPromptReplyData struct {
	Id     int64  `json:"id"`
	KfId   string `json:"kf_id"`
	Prompt string `json:"prompt"`
}

type ListPromptReply struct {
	List []ListPromptReplyData `json:"list"`
}

type SyncWechatUserReq struct {
}

type SyncWechatUserReply struct {
	Message string `json:"message"`
}
